import Toploader from "@/components/TopLoading";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/utils/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-gray-50 ${inter.className}`}>
        <Toploader />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
