import Toploader from "@/components/TopLoading";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/utils/AuthProvider";
import { Toaster } from "react-hot-toast";

export const revalidate = 0;

export const metadata = {
  title: "Eco-MART",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-gray-50 ${inter.className}`}>
        <Toploader />
        <Toaster />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
